"""dnapaymentspartnerreportingsettlementapis.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from apimatic_core.configurations.global_configuration import (
    GlobalConfiguration,
)
from apimatic_core.decorators.lazy_property import (
    LazyProperty,
)

from dnapaymentspartnerreportingsettlementapis.apis.authentication_api import (
    AuthenticationApi,
)
from dnapaymentspartnerreportingsettlementapis.apis.base_api import (
    BaseApi,
)
from dnapaymentspartnerreportingsettlementapis.apis.ecommerce_transactions_api import (
    EcommerceTransactionsApi,
)
from dnapaymentspartnerreportingsettlementapis.apis.merchants_api import (
    MerchantsApi,
)
from dnapaymentspartnerreportingsettlementapis.apis.oauth_authorization_api import (
    OauthAuthorizationApi,
)
from dnapaymentspartnerreportingsettlementapis.apis.pos_transactions_api import (
    PosTransactionsApi,
)
from dnapaymentspartnerreportingsettlementapis.apis.settlements_api import (
    SettlementsApi,
)
from dnapaymentspartnerreportingsettlementapis.configuration import (
    Configuration,
    Environment,
)
from dnapaymentspartnerreportingsettlementapis.http.auth.oauth_2 import (
    Oauth2,
)


class DnapaymentspartnerreportingsettlementapisClient(object):
    """Client that provide access to the
    DnapaymentspartnerreportingsettlementapisClient APIs.
    """

    @LazyProperty
    def authentication(self):
        """Provide access to the AuthenticationApi endpoints."""
        return AuthenticationApi(self.global_configuration)

    @LazyProperty
    def merchants(self):
        """Provide access to the MerchantsApi endpoints."""
        return MerchantsApi(self.global_configuration)

    @LazyProperty
    def ecommerce_transactions(self):
        """Provide access to the EcommerceTransactionsApi endpoints."""
        return EcommerceTransactionsApi(self.global_configuration)

    @LazyProperty
    def pos_transactions(self):
        """Provide access to the PosTransactionsApi endpoints."""
        return PosTransactionsApi(self.global_configuration)

    @LazyProperty
    def settlements(self):
        """Provide access to the SettlementsApi endpoints."""
        return SettlementsApi(self.global_configuration)

    @LazyProperty
    def oauth_authorization(self):
        """Provide access to the OauthAuthorizationApi endpoints."""
        return OauthAuthorizationApi(self.global_configuration)

    @property
    def bearer_auth(self):
        """Provide access to the BearerAuth auth manager."""
        return self.auth_managers["BearerAuth"]

    def __init__(self, http_client_instance=None,
                 override_http_client_configuration=False, http_call_back=None,
                 timeout=30, max_retries=0, backoff_factor=2,
                 retry_statuses=None, retry_methods=None, proxy_settings=None,
                 logging_configuration=None, environment=Environment.PRODUCTION,
                 client_credentials_auth_credentials=None, config=None):
        """Initialize a new instance of DnapaymentspartnerreportingsettlementapisClient."""
        self.config = config or Configuration(
            http_client_instance=http_client_instance,
            override_http_client_configuration=override_http_client_configuration,
            http_call_back=http_call_back, timeout=timeout,
            max_retries=max_retries, backoff_factor=backoff_factor,
            retry_statuses=retry_statuses, retry_methods=retry_methods,
            proxy_settings=proxy_settings,
            logging_configuration=logging_configuration,
            environment=environment,
            client_credentials_auth_credentials=client_credentials_auth_credentials)

        self.global_configuration = GlobalConfiguration(self.config)\
            .global_errors(BaseApi.global_errors())\
            .base_uri_executor(self.config.get_base_uri)\
            .user_agent(BaseApi.user_agent(),
                BaseApi.user_agent_parameters())

        self.auth_managers = {
            "BearerAuth": Oauth2(
                self.config.client_credentials_auth_credentials,
                self.global_configuration),
        }
        self.global_configuration =\
            self.global_configuration.auth_managers(self.auth_managers)

    @classmethod
    def from_environment(cls, dotenv_path=None, **overrides):
        """Create a client instance using environment variables.

        Returns:
            DnapaymentspartnerreportingsettlementapisClient instance.

        """
        return cls(config=Configuration
            .from_environment(dotenv_path=dotenv_path, **overrides))
