"""dnapaymentspartnerreportingsettlementapis.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from dnapaymentspartnerreportingsettlementapis.api_helper import (
    APIHelper,
)


class AuthTokenResponse(object):
    """Implementation of the 'AuthTokenResponse' model.

    Attributes:
        access_token (str): Access token to be used in subsequent API calls.
        expires_in (int): Number of seconds until the access_token expires.
        refresh_token (str): Reserved for future use.
        scope (str): The model property of type str.
        token_type (TokenType): The model property of type TokenType.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "access_token": "access_token",
        "expires_in": "expires_in",
        "refresh_token": "refresh_token",
        "scope": "scope",
        "token_type": "token_type",
    }

    _optionals = [
        "access_token",
        "expires_in",
        "refresh_token",
        "scope",
        "token_type",
    ]

    def __init__(
        self,
        access_token=APIHelper.SKIP,
        expires_in=APIHelper.SKIP,
        refresh_token=APIHelper.SKIP,
        scope=APIHelper.SKIP,
        token_type=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a AuthTokenResponse instance."""
        # Initialize members of the class
        if access_token is not APIHelper.SKIP:
            self.access_token = access_token
        if expires_in is not APIHelper.SKIP:
            self.expires_in = expires_in
        if refresh_token is not APIHelper.SKIP:
            self.refresh_token = refresh_token
        if scope is not APIHelper.SKIP:
            self.scope = scope
        if token_type is not APIHelper.SKIP:
            self.token_type = token_type

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        access_token =\
            dictionary.get("access_token")\
            if dictionary.get("access_token")\
                else APIHelper.SKIP
        expires_in =\
            dictionary.get("expires_in")\
            if dictionary.get("expires_in")\
                else APIHelper.SKIP
        refresh_token =\
            dictionary.get("refresh_token")\
            if dictionary.get("refresh_token")\
                else APIHelper.SKIP
        scope =\
            dictionary.get("scope")\
            if dictionary.get("scope")\
                else APIHelper.SKIP
        token_type =\
            dictionary.get("token_type")\
            if dictionary.get("token_type")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(access_token,
                   expires_in,
                   refresh_token,
                   scope,
                   token_type,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _access_token=(
            self.access_token
            if hasattr(self, "access_token")
            else None
        )
        _expires_in=(
            self.expires_in
            if hasattr(self, "expires_in")
            else None
        )
        _refresh_token=(
            self.refresh_token
            if hasattr(self, "refresh_token")
            else None
        )
        _scope=(
            self.scope
            if hasattr(self, "scope")
            else None
        )
        _token_type=(
            self.token_type
            if hasattr(self, "token_type")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"access_token={_access_token!r}, "
            f"expires_in={_expires_in!r}, "
            f"refresh_token={_refresh_token!r}, "
            f"scope={_scope!r}, "
            f"token_type={_token_type!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _access_token=(
            self.access_token
            if hasattr(self, "access_token")
            else None
        )
        _expires_in=(
            self.expires_in
            if hasattr(self, "expires_in")
            else None
        )
        _refresh_token=(
            self.refresh_token
            if hasattr(self, "refresh_token")
            else None
        )
        _scope=(
            self.scope
            if hasattr(self, "scope")
            else None
        )
        _token_type=(
            self.token_type
            if hasattr(self, "token_type")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"access_token={_access_token!s}, "
            f"expires_in={_expires_in!s}, "
            f"refresh_token={_refresh_token!s}, "
            f"scope={_scope!s}, "
            f"token_type={_token_type!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
