"""dnapaymentspartnerreportingsettlementapis.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from dnapaymentspartnerreportingsettlementapis.api_helper import (
    APIHelper,
)


class AuthTokenRequest(object):
    """Implementation of the 'AuthTokenRequest' model.

    Attributes:
        grant_type (str): Authorisation type required to confirm the action required.
        scope (str): Scope of the action to be performed with the credentials.
        client_id (str): Provided to the integrator following successful creation of
            a test account.
        client_secret (str): Provided to the integrator following successful creation
            of a test account.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "grant_type": "grant_type",
        "scope": "scope",
        "client_id": "client_id",
        "client_secret": "client_secret",
    }

    def __init__(
        self,
        client_id=None,
        client_secret=None,
        additional_properties=None):
        """Initialize a AuthTokenRequest instance."""
        # Initialize members of the class
        self.grant_type = "client_credentials"
        self.scope = "partners_reporting"
        self.client_id = client_id
        self.client_secret = client_secret

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        client_id =\
            dictionary.get("client_id")\
            if dictionary.get("client_id")\
                else None
        client_secret =\
            dictionary.get("client_secret")\
            if dictionary.get("client_secret")\
                else None

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(client_id,
                   client_secret,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _grant_type=self.grant_type
        _scope=self.scope
        _client_id=self.client_id
        _client_secret=self.client_secret
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"grant_type={_grant_type!r}, "
            f"scope={_scope!r}, "
            f"client_id={_client_id!r}, "
            f"client_secret={_client_secret!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _grant_type=self.grant_type
        _scope=self.scope
        _client_id=self.client_id
        _client_secret=self.client_secret
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"grant_type={_grant_type!s}, "
            f"scope={_scope!s}, "
            f"client_id={_client_id!s}, "
            f"client_secret={_client_secret!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
