"""dnapaymentspartnerreportingsettlementapis.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class CaptureMethod(object):
    """Implementation of the 'CaptureMethod' enum.

    Capture method for the transaction.

    Attributes:
        ECOM: The enum member of type str.
        ECOMPAYBYBANKAPP: The enum member of type str.
        ECOMOPENBANKING: The enum member of type str.
        ECOMKLARNA: The enum member of type str.
        MOTO: The enum member of type str.
        RECURRING: The enum member of type str.
        POS: The enum member of type str.
        POSCONTACTLESS: The enum member of type str.
        STORED: The enum member of type str.
        POSOPENBANKING: The enum member of type str.
        POSALIPAY: The enum member of type str.

    """

    ECOM = "ecom"

    ECOMPAYBYBANKAPP = "ecom-paybybankapp"

    ECOMOPENBANKING = "ecom-openbanking"

    ECOMKLARNA = "ecom-klarna"

    MOTO = "moto"

    RECURRING = "recurring"

    POS = "pos"

    POSCONTACTLESS = "pos-contactless"

    STORED = "stored"

    POSOPENBANKING = "pos-openbanking"

    POSALIPAY = "pos-alipay"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
