"""dnapaymentspartnerreportingsettlementapis.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from dnapaymentspartnerreportingsettlementapis.api_helper import (
    APIHelper,
)
from dnapaymentspartnerreportingsettlementapis.models.ecommerce_transaction import (
    EcommerceTransaction,
)


class EcommerceTransactionsResponse(object):
    """Implementation of the 'EcommerceTransactionsResponse' model.

    Attributes:
        total_count (int): Total count of records for the requested time period.
        data (List[EcommerceTransaction]): The model property of type
            List[EcommerceTransaction].
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "total_count": "totalCount",
        "data": "data",
    }

    _optionals = [
        "total_count",
        "data",
    ]

    def __init__(
        self,
        total_count=APIHelper.SKIP,
        data=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a EcommerceTransactionsResponse instance."""
        # Initialize members of the class
        if total_count is not APIHelper.SKIP:
            self.total_count = total_count
        if data is not APIHelper.SKIP:
            self.data = data

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        total_count =\
            dictionary.get("totalCount")\
            if dictionary.get("totalCount")\
                else APIHelper.SKIP
        data = None
        if dictionary.get("data") is not None:
            data = [
                EcommerceTransaction.from_dictionary(x)
                    for x in dictionary.get("data")
            ]
        else:
            data = APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(total_count,
                   data,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _total_count=(
            self.total_count
            if hasattr(self, "total_count")
            else None
        )
        _data=(
            self.data
            if hasattr(self, "data")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"total_count={_total_count!r}, "
            f"data={_data!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _total_count=(
            self.total_count
            if hasattr(self, "total_count")
            else None
        )
        _data=(
            self.data
            if hasattr(self, "data")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"total_count={_total_count!s}, "
            f"data={_data!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
