"""dnapaymentspartnerreportingsettlementapis.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from dnapaymentspartnerreportingsettlementapis.api_helper import (
    APIHelper,
)


class EcommerceTransaction(object):
    """Implementation of the 'EcommerceTransaction' model.

    Attributes:
        id (str): Unique transaction ID.
        merchant_id (str): Unique ID for the merchant, allocated by DNA Payments.
        merchant_name (str): Name of the merchant.
        merchant_reference (str): Unique order number allocated by the merchant.
        amount (float): Original requested transaction amount.
        currency (str): Transaction currency code. ISO 4217 format, e.g. GBP.
        created_date (datetime): Date/time the transaction was created on the DNA
            Platform.
        auth_date (datetime): Date/time the transaction authorisation was attempted
            with the acquirer.
        confirm_date (datetime): Date/time the transaction was confirmed on the DNA
            Platform.
        processed_date (datetime): Date/time the transaction was processed (last
            action performed, e.g. charged/settled/refunded).
        processed_amount (float): Charged/Settled/Refunded amount.
        mtype (str): Transaction type. See the Ecommerce Reference documentation for
            the full list (not available at spec-generation time).
        status (str): Status of the transaction. See the Ecommerce Reference
            documentation for the full list (not available at spec-generation time).
        payment_method (str): Payment method used on the transaction. See the
            Ecommerce Reference documentation for the full list (not available at
            spec-generation time).
        card_type (str): Type of card used in the transaction.
        card_scheme (str): Card scheme used in the transaction, e.g. mastercard, visa.
        card_mask (str): Masked PAN for the payment card used; contains the first six
            and last four digits.
        issuer (str): Issuer of the payment card used in the transaction.
        issuer_country (str): Country in which the payment card was issued. ISO
            3166-1 alpha-3.
        response_code (str): Response code returned by the acquirer during
            authorisation.
        auth_code (str): Authorisation code issued by the acquirer/issuer for the
            transaction, when applicable.
        avs_result (str): Result of the Address Verification System (AVS) check.
        avs_house_number_result (str): Result of the AVS 'House Number' check.
        avs_postcode_result (str): Result of the AVS 'Post Code' check.
        csc_result (str): Result of the Cardholder Security Code (CSC) check.
        payer_authentication_result (str): Result of the Payer Authentication
            enrollment/authentication checks, format Enrollment/Authentication e.g.
            Y/A.
        payer_ip (str): IP address of the consumer. Subject to GDPR confirmation; may
            be removed.
        payer_name (str): Consumer name. Subject to GDPR confirmation; may be removed.
        payer_email (str): Email address of the consumer. Subject to GDPR
            confirmation; may be removed.
        payer_phone (str): Phone number of the consumer. Subject to GDPR
            confirmation; may be removed.
        ip_country (str): Country where the purchase was made. Subject to GDPR
            confirmation; may be removed.
        ip_city (str): City where the purchase was made. Subject to GDPR
            confirmation; may be removed.
        ip_latitude (float): Locational data – latitude. Subject to GDPR
            confirmation; may be removed.
        ip_longitude (float): Locational data – longitude. Subject to GDPR
            confirmation; may be removed.
        merchant_custom_data (str): Base64-encoded custom data supplied by the
            merchant with the transaction request. Max 1024 bytes. Not used for any
            processing, purely recorded.
        description (str): Descriptive text passed in the Payment Request for the
            transaction.
        parent_transaction_id (str): If the transaction is a full/partial refund, the
            transactionId of the original/linked sale.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id": "id",
        "merchant_id": "merchantId",
        "merchant_name": "merchantName",
        "merchant_reference": "merchantReference",
        "amount": "amount",
        "currency": "currency",
        "created_date": "createdDate",
        "auth_date": "authDate",
        "confirm_date": "confirmDate",
        "processed_date": "processedDate",
        "processed_amount": "processedAmount",
        "mtype": "type",
        "status": "status",
        "payment_method": "paymentMethod",
        "card_type": "cardType",
        "card_scheme": "cardScheme",
        "card_mask": "cardMask",
        "issuer": "issuer",
        "issuer_country": "issuerCountry",
        "response_code": "responseCode",
        "auth_code": "authCode",
        "avs_result": "avsResult",
        "avs_house_number_result": "avsHouseNumberResult",
        "avs_postcode_result": "avsPostcodeResult",
        "csc_result": "cscResult",
        "payer_authentication_result": "payerAuthenticationResult",
        "payer_ip": "payerIp",
        "payer_name": "payerName",
        "payer_email": "payerEmail",
        "payer_phone": "payerPhone",
        "ip_country": "ipCountry",
        "ip_city": "ipCity",
        "ip_latitude": "ipLatitude",
        "ip_longitude": "ipLongitude",
        "merchant_custom_data": "merchantCustomData",
        "description": "description",
        "parent_transaction_id": "parentTransactionId",
    }

    _optionals = [
        "id",
        "merchant_id",
        "merchant_name",
        "merchant_reference",
        "amount",
        "currency",
        "created_date",
        "auth_date",
        "confirm_date",
        "processed_date",
        "processed_amount",
        "mtype",
        "status",
        "payment_method",
        "card_type",
        "card_scheme",
        "card_mask",
        "issuer",
        "issuer_country",
        "response_code",
        "auth_code",
        "avs_result",
        "avs_house_number_result",
        "avs_postcode_result",
        "csc_result",
        "payer_authentication_result",
        "payer_ip",
        "payer_name",
        "payer_email",
        "payer_phone",
        "ip_country",
        "ip_city",
        "ip_latitude",
        "ip_longitude",
        "merchant_custom_data",
        "description",
        "parent_transaction_id",
    ]

    _nullables = [
        "auth_date",
        "confirm_date",
        "processed_date",
        "card_type",
        "card_scheme",
        "card_mask",
        "issuer",
        "issuer_country",
        "response_code",
        "auth_code",
        "avs_result",
        "avs_house_number_result",
        "avs_postcode_result",
        "csc_result",
        "payer_authentication_result",
        "payer_ip",
        "payer_name",
        "payer_email",
        "payer_phone",
        "ip_country",
        "ip_city",
        "ip_latitude",
        "ip_longitude",
        "merchant_custom_data",
        "description",
        "parent_transaction_id",
    ]

    def __init__(
        self,
        id=APIHelper.SKIP,
        merchant_id=APIHelper.SKIP,
        merchant_name=APIHelper.SKIP,
        merchant_reference=APIHelper.SKIP,
        amount=APIHelper.SKIP,
        currency=APIHelper.SKIP,
        created_date=APIHelper.SKIP,
        auth_date=APIHelper.SKIP,
        confirm_date=APIHelper.SKIP,
        processed_date=APIHelper.SKIP,
        processed_amount=APIHelper.SKIP,
        mtype=APIHelper.SKIP,
        status=APIHelper.SKIP,
        payment_method=APIHelper.SKIP,
        card_type=APIHelper.SKIP,
        card_scheme=APIHelper.SKIP,
        card_mask=APIHelper.SKIP,
        issuer=APIHelper.SKIP,
        issuer_country=APIHelper.SKIP,
        response_code=APIHelper.SKIP,
        auth_code=APIHelper.SKIP,
        avs_result=APIHelper.SKIP,
        avs_house_number_result=APIHelper.SKIP,
        avs_postcode_result=APIHelper.SKIP,
        csc_result=APIHelper.SKIP,
        payer_authentication_result=APIHelper.SKIP,
        payer_ip=APIHelper.SKIP,
        payer_name=APIHelper.SKIP,
        payer_email=APIHelper.SKIP,
        payer_phone=APIHelper.SKIP,
        ip_country=APIHelper.SKIP,
        ip_city=APIHelper.SKIP,
        ip_latitude=APIHelper.SKIP,
        ip_longitude=APIHelper.SKIP,
        merchant_custom_data=APIHelper.SKIP,
        description=APIHelper.SKIP,
        parent_transaction_id=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a EcommerceTransaction instance."""
        # Initialize members of the class
        if id is not APIHelper.SKIP:
            self.id = id
        if merchant_id is not APIHelper.SKIP:
            self.merchant_id = merchant_id
        if merchant_name is not APIHelper.SKIP:
            self.merchant_name = merchant_name
        if merchant_reference is not APIHelper.SKIP:
            self.merchant_reference = merchant_reference
        if amount is not APIHelper.SKIP:
            self.amount = amount
        if currency is not APIHelper.SKIP:
            self.currency = currency
        if created_date is not APIHelper.SKIP:
            self.created_date =\
                 APIHelper.apply_datetime_converter(
                created_date, APIHelper.RFC3339DateTime)\
                 if created_date else None
        if auth_date is not APIHelper.SKIP:
            self.auth_date =\
                 APIHelper.apply_datetime_converter(
                auth_date, APIHelper.RFC3339DateTime)\
                 if auth_date else None
        if confirm_date is not APIHelper.SKIP:
            self.confirm_date =\
                 APIHelper.apply_datetime_converter(
                confirm_date, APIHelper.RFC3339DateTime)\
                 if confirm_date else None
        if processed_date is not APIHelper.SKIP:
            self.processed_date =\
                 APIHelper.apply_datetime_converter(
                processed_date, APIHelper.RFC3339DateTime)\
                 if processed_date else None
        if processed_amount is not APIHelper.SKIP:
            self.processed_amount = processed_amount
        if mtype is not APIHelper.SKIP:
            self.mtype = mtype
        if status is not APIHelper.SKIP:
            self.status = status
        if payment_method is not APIHelper.SKIP:
            self.payment_method = payment_method
        if card_type is not APIHelper.SKIP:
            self.card_type = card_type
        if card_scheme is not APIHelper.SKIP:
            self.card_scheme = card_scheme
        if card_mask is not APIHelper.SKIP:
            self.card_mask = card_mask
        if issuer is not APIHelper.SKIP:
            self.issuer = issuer
        if issuer_country is not APIHelper.SKIP:
            self.issuer_country = issuer_country
        if response_code is not APIHelper.SKIP:
            self.response_code = response_code
        if auth_code is not APIHelper.SKIP:
            self.auth_code = auth_code
        if avs_result is not APIHelper.SKIP:
            self.avs_result = avs_result
        if avs_house_number_result is not APIHelper.SKIP:
            self.avs_house_number_result = avs_house_number_result
        if avs_postcode_result is not APIHelper.SKIP:
            self.avs_postcode_result = avs_postcode_result
        if csc_result is not APIHelper.SKIP:
            self.csc_result = csc_result
        if payer_authentication_result is not APIHelper.SKIP:
            self.payer_authentication_result = payer_authentication_result
        if payer_ip is not APIHelper.SKIP:
            self.payer_ip = payer_ip
        if payer_name is not APIHelper.SKIP:
            self.payer_name = payer_name
        if payer_email is not APIHelper.SKIP:
            self.payer_email = payer_email
        if payer_phone is not APIHelper.SKIP:
            self.payer_phone = payer_phone
        if ip_country is not APIHelper.SKIP:
            self.ip_country = ip_country
        if ip_city is not APIHelper.SKIP:
            self.ip_city = ip_city
        if ip_latitude is not APIHelper.SKIP:
            self.ip_latitude = ip_latitude
        if ip_longitude is not APIHelper.SKIP:
            self.ip_longitude = ip_longitude
        if merchant_custom_data is not APIHelper.SKIP:
            self.merchant_custom_data = merchant_custom_data
        if description is not APIHelper.SKIP:
            self.description = description
        if parent_transaction_id is not APIHelper.SKIP:
            self.parent_transaction_id = parent_transaction_id

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else APIHelper.SKIP
        merchant_id =\
            dictionary.get("merchantId")\
            if dictionary.get("merchantId")\
                else APIHelper.SKIP
        merchant_name =\
            dictionary.get("merchantName")\
            if dictionary.get("merchantName")\
                else APIHelper.SKIP
        merchant_reference =\
            dictionary.get("merchantReference")\
            if dictionary.get("merchantReference")\
                else APIHelper.SKIP
        amount =\
            dictionary.get("amount")\
            if dictionary.get("amount")\
                else APIHelper.SKIP
        currency =\
            dictionary.get("currency")\
            if dictionary.get("currency")\
                else APIHelper.SKIP
        created_date = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("createdDate")).datetime\
            if dictionary.get("createdDate") else APIHelper.SKIP
        if "authDate" in dictionary.keys():
            auth_date = APIHelper.RFC3339DateTime.from_value(
                dictionary.get("authDate")).datetime\
                if dictionary.get("authDate") else None

        else:
            auth_date = APIHelper.SKIP
        if "confirmDate" in dictionary.keys():
            confirm_date = APIHelper.RFC3339DateTime.from_value(
                dictionary.get("confirmDate")).datetime\
                if dictionary.get("confirmDate") else None

        else:
            confirm_date = APIHelper.SKIP
        if "processedDate" in dictionary.keys():
            processed_date = APIHelper.RFC3339DateTime.from_value(
                dictionary.get("processedDate")).datetime\
                if dictionary.get("processedDate") else None

        else:
            processed_date = APIHelper.SKIP
        processed_amount =\
            dictionary.get("processedAmount")\
            if dictionary.get("processedAmount")\
                else APIHelper.SKIP
        mtype =\
            dictionary.get("type")\
            if dictionary.get("type")\
                else APIHelper.SKIP
        status =\
            dictionary.get("status")\
            if dictionary.get("status")\
                else APIHelper.SKIP
        payment_method =\
            dictionary.get("paymentMethod")\
            if dictionary.get("paymentMethod")\
                else APIHelper.SKIP
        card_type =\
            dictionary.get("cardType")\
            if "cardType" in dictionary.keys()\
                else APIHelper.SKIP
        card_scheme =\
            dictionary.get("cardScheme")\
            if "cardScheme" in dictionary.keys()\
                else APIHelper.SKIP
        card_mask =\
            dictionary.get("cardMask")\
            if "cardMask" in dictionary.keys()\
                else APIHelper.SKIP
        issuer =\
            dictionary.get("issuer")\
            if "issuer" in dictionary.keys()\
                else APIHelper.SKIP
        issuer_country =\
            dictionary.get("issuerCountry")\
            if "issuerCountry" in dictionary.keys()\
                else APIHelper.SKIP
        response_code =\
            dictionary.get("responseCode")\
            if "responseCode" in dictionary.keys()\
                else APIHelper.SKIP
        auth_code =\
            dictionary.get("authCode")\
            if "authCode" in dictionary.keys()\
                else APIHelper.SKIP
        avs_result =\
            dictionary.get("avsResult")\
            if "avsResult" in dictionary.keys()\
                else APIHelper.SKIP
        avs_house_number_result =\
            dictionary.get("avsHouseNumberResult")\
            if "avsHouseNumberResult" in dictionary.keys()\
                else APIHelper.SKIP
        avs_postcode_result =\
            dictionary.get("avsPostcodeResult")\
            if "avsPostcodeResult" in dictionary.keys()\
                else APIHelper.SKIP
        csc_result =\
            dictionary.get("cscResult")\
            if "cscResult" in dictionary.keys()\
                else APIHelper.SKIP
        payer_authentication_result =\
            dictionary.get("payerAuthenticationResult")\
            if "payerAuthenticationResult" in dictionary.keys()\
                else APIHelper.SKIP
        payer_ip =\
            dictionary.get("payerIp")\
            if "payerIp" in dictionary.keys()\
                else APIHelper.SKIP
        payer_name =\
            dictionary.get("payerName")\
            if "payerName" in dictionary.keys()\
                else APIHelper.SKIP
        payer_email =\
            dictionary.get("payerEmail")\
            if "payerEmail" in dictionary.keys()\
                else APIHelper.SKIP
        payer_phone =\
            dictionary.get("payerPhone")\
            if "payerPhone" in dictionary.keys()\
                else APIHelper.SKIP
        ip_country =\
            dictionary.get("ipCountry")\
            if "ipCountry" in dictionary.keys()\
                else APIHelper.SKIP
        ip_city =\
            dictionary.get("ipCity")\
            if "ipCity" in dictionary.keys()\
                else APIHelper.SKIP
        ip_latitude =\
            dictionary.get("ipLatitude")\
            if "ipLatitude" in dictionary.keys()\
                else APIHelper.SKIP
        ip_longitude =\
            dictionary.get("ipLongitude")\
            if "ipLongitude" in dictionary.keys()\
                else APIHelper.SKIP
        merchant_custom_data =\
            dictionary.get("merchantCustomData")\
            if "merchantCustomData" in dictionary.keys()\
                else APIHelper.SKIP
        description =\
            dictionary.get("description")\
            if "description" in dictionary.keys()\
                else APIHelper.SKIP
        parent_transaction_id =\
            dictionary.get("parentTransactionId")\
            if "parentTransactionId" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(id,
                   merchant_id,
                   merchant_name,
                   merchant_reference,
                   amount,
                   currency,
                   created_date,
                   auth_date,
                   confirm_date,
                   processed_date,
                   processed_amount,
                   mtype,
                   status,
                   payment_method,
                   card_type,
                   card_scheme,
                   card_mask,
                   issuer,
                   issuer_country,
                   response_code,
                   auth_code,
                   avs_result,
                   avs_house_number_result,
                   avs_postcode_result,
                   csc_result,
                   payer_authentication_result,
                   payer_ip,
                   payer_name,
                   payer_email,
                   payer_phone,
                   ip_country,
                   ip_city,
                   ip_latitude,
                   ip_longitude,
                   merchant_custom_data,
                   description,
                   parent_transaction_id,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _merchant_id=(
            self.merchant_id
            if hasattr(self, "merchant_id")
            else None
        )
        _merchant_name=(
            self.merchant_name
            if hasattr(self, "merchant_name")
            else None
        )
        _merchant_reference=(
            self.merchant_reference
            if hasattr(self, "merchant_reference")
            else None
        )
        _amount=(
            self.amount
            if hasattr(self, "amount")
            else None
        )
        _currency=(
            self.currency
            if hasattr(self, "currency")
            else None
        )
        _created_date=(
            self.created_date
            if hasattr(self, "created_date")
            else None
        )
        _auth_date=(
            self.auth_date
            if hasattr(self, "auth_date")
            else None
        )
        _confirm_date=(
            self.confirm_date
            if hasattr(self, "confirm_date")
            else None
        )
        _processed_date=(
            self.processed_date
            if hasattr(self, "processed_date")
            else None
        )
        _processed_amount=(
            self.processed_amount
            if hasattr(self, "processed_amount")
            else None
        )
        _mtype=(
            self.mtype
            if hasattr(self, "mtype")
            else None
        )
        _status=(
            self.status
            if hasattr(self, "status")
            else None
        )
        _payment_method=(
            self.payment_method
            if hasattr(self, "payment_method")
            else None
        )
        _card_type=(
            self.card_type
            if hasattr(self, "card_type")
            else None
        )
        _card_scheme=(
            self.card_scheme
            if hasattr(self, "card_scheme")
            else None
        )
        _card_mask=(
            self.card_mask
            if hasattr(self, "card_mask")
            else None
        )
        _issuer=(
            self.issuer
            if hasattr(self, "issuer")
            else None
        )
        _issuer_country=(
            self.issuer_country
            if hasattr(self, "issuer_country")
            else None
        )
        _response_code=(
            self.response_code
            if hasattr(self, "response_code")
            else None
        )
        _auth_code=(
            self.auth_code
            if hasattr(self, "auth_code")
            else None
        )
        _avs_result=(
            self.avs_result
            if hasattr(self, "avs_result")
            else None
        )
        _avs_house_number_result=(
            self.avs_house_number_result
            if hasattr(self, "avs_house_number_result")
            else None
        )
        _avs_postcode_result=(
            self.avs_postcode_result
            if hasattr(self, "avs_postcode_result")
            else None
        )
        _csc_result=(
            self.csc_result
            if hasattr(self, "csc_result")
            else None
        )
        _payer_authentication_result=(
            self.payer_authentication_result
            if hasattr(self, "payer_authentication_result")
            else None
        )
        _payer_ip=(
            self.payer_ip
            if hasattr(self, "payer_ip")
            else None
        )
        _payer_name=(
            self.payer_name
            if hasattr(self, "payer_name")
            else None
        )
        _payer_email=(
            self.payer_email
            if hasattr(self, "payer_email")
            else None
        )
        _payer_phone=(
            self.payer_phone
            if hasattr(self, "payer_phone")
            else None
        )
        _ip_country=(
            self.ip_country
            if hasattr(self, "ip_country")
            else None
        )
        _ip_city=(
            self.ip_city
            if hasattr(self, "ip_city")
            else None
        )
        _ip_latitude=(
            self.ip_latitude
            if hasattr(self, "ip_latitude")
            else None
        )
        _ip_longitude=(
            self.ip_longitude
            if hasattr(self, "ip_longitude")
            else None
        )
        _merchant_custom_data=(
            self.merchant_custom_data
            if hasattr(self, "merchant_custom_data")
            else None
        )
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _parent_transaction_id=(
            self.parent_transaction_id
            if hasattr(self, "parent_transaction_id")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"id={_id!r}, "
            f"merchant_id={_merchant_id!r}, "
            f"merchant_name={_merchant_name!r}, "
            f"merchant_reference={_merchant_reference!r}, "
            f"amount={_amount!r}, "
            f"currency={_currency!r}, "
            f"created_date={_created_date!r}, "
            f"auth_date={_auth_date!r}, "
            f"confirm_date={_confirm_date!r}, "
            f"processed_date={_processed_date!r}, "
            f"processed_amount={_processed_amount!r}, "
            f"mtype={_mtype!r}, "
            f"status={_status!r}, "
            f"payment_method={_payment_method!r}, "
            f"card_type={_card_type!r}, "
            f"card_scheme={_card_scheme!r}, "
            f"card_mask={_card_mask!r}, "
            f"issuer={_issuer!r}, "
            f"issuer_country={_issuer_country!r}, "
            f"response_code={_response_code!r}, "
            f"auth_code={_auth_code!r}, "
            f"avs_result={_avs_result!r}, "
            f"avs_house_number_result={_avs_house_number_result!r}, "
            f"avs_postcode_result={_avs_postcode_result!r}, "
            f"csc_result={_csc_result!r}, "
            f"payer_authentication_result={_payer_authentication_result!r}, "
            f"payer_ip={_payer_ip!r}, "
            f"payer_name={_payer_name!r}, "
            f"payer_email={_payer_email!r}, "
            f"payer_phone={_payer_phone!r}, "
            f"ip_country={_ip_country!r}, "
            f"ip_city={_ip_city!r}, "
            f"ip_latitude={_ip_latitude!r}, "
            f"ip_longitude={_ip_longitude!r}, "
            f"merchant_custom_data={_merchant_custom_data!r}, "
            f"description={_description!r}, "
            f"parent_transaction_id={_parent_transaction_id!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _merchant_id=(
            self.merchant_id
            if hasattr(self, "merchant_id")
            else None
        )
        _merchant_name=(
            self.merchant_name
            if hasattr(self, "merchant_name")
            else None
        )
        _merchant_reference=(
            self.merchant_reference
            if hasattr(self, "merchant_reference")
            else None
        )
        _amount=(
            self.amount
            if hasattr(self, "amount")
            else None
        )
        _currency=(
            self.currency
            if hasattr(self, "currency")
            else None
        )
        _created_date=(
            self.created_date
            if hasattr(self, "created_date")
            else None
        )
        _auth_date=(
            self.auth_date
            if hasattr(self, "auth_date")
            else None
        )
        _confirm_date=(
            self.confirm_date
            if hasattr(self, "confirm_date")
            else None
        )
        _processed_date=(
            self.processed_date
            if hasattr(self, "processed_date")
            else None
        )
        _processed_amount=(
            self.processed_amount
            if hasattr(self, "processed_amount")
            else None
        )
        _mtype=(
            self.mtype
            if hasattr(self, "mtype")
            else None
        )
        _status=(
            self.status
            if hasattr(self, "status")
            else None
        )
        _payment_method=(
            self.payment_method
            if hasattr(self, "payment_method")
            else None
        )
        _card_type=(
            self.card_type
            if hasattr(self, "card_type")
            else None
        )
        _card_scheme=(
            self.card_scheme
            if hasattr(self, "card_scheme")
            else None
        )
        _card_mask=(
            self.card_mask
            if hasattr(self, "card_mask")
            else None
        )
        _issuer=(
            self.issuer
            if hasattr(self, "issuer")
            else None
        )
        _issuer_country=(
            self.issuer_country
            if hasattr(self, "issuer_country")
            else None
        )
        _response_code=(
            self.response_code
            if hasattr(self, "response_code")
            else None
        )
        _auth_code=(
            self.auth_code
            if hasattr(self, "auth_code")
            else None
        )
        _avs_result=(
            self.avs_result
            if hasattr(self, "avs_result")
            else None
        )
        _avs_house_number_result=(
            self.avs_house_number_result
            if hasattr(self, "avs_house_number_result")
            else None
        )
        _avs_postcode_result=(
            self.avs_postcode_result
            if hasattr(self, "avs_postcode_result")
            else None
        )
        _csc_result=(
            self.csc_result
            if hasattr(self, "csc_result")
            else None
        )
        _payer_authentication_result=(
            self.payer_authentication_result
            if hasattr(self, "payer_authentication_result")
            else None
        )
        _payer_ip=(
            self.payer_ip
            if hasattr(self, "payer_ip")
            else None
        )
        _payer_name=(
            self.payer_name
            if hasattr(self, "payer_name")
            else None
        )
        _payer_email=(
            self.payer_email
            if hasattr(self, "payer_email")
            else None
        )
        _payer_phone=(
            self.payer_phone
            if hasattr(self, "payer_phone")
            else None
        )
        _ip_country=(
            self.ip_country
            if hasattr(self, "ip_country")
            else None
        )
        _ip_city=(
            self.ip_city
            if hasattr(self, "ip_city")
            else None
        )
        _ip_latitude=(
            self.ip_latitude
            if hasattr(self, "ip_latitude")
            else None
        )
        _ip_longitude=(
            self.ip_longitude
            if hasattr(self, "ip_longitude")
            else None
        )
        _merchant_custom_data=(
            self.merchant_custom_data
            if hasattr(self, "merchant_custom_data")
            else None
        )
        _description=(
            self.description
            if hasattr(self, "description")
            else None
        )
        _parent_transaction_id=(
            self.parent_transaction_id
            if hasattr(self, "parent_transaction_id")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"id={_id!s}, "
            f"merchant_id={_merchant_id!s}, "
            f"merchant_name={_merchant_name!s}, "
            f"merchant_reference={_merchant_reference!s}, "
            f"amount={_amount!s}, "
            f"currency={_currency!s}, "
            f"created_date={_created_date!s}, "
            f"auth_date={_auth_date!s}, "
            f"confirm_date={_confirm_date!s}, "
            f"processed_date={_processed_date!s}, "
            f"processed_amount={_processed_amount!s}, "
            f"mtype={_mtype!s}, "
            f"status={_status!s}, "
            f"payment_method={_payment_method!s}, "
            f"card_type={_card_type!s}, "
            f"card_scheme={_card_scheme!s}, "
            f"card_mask={_card_mask!s}, "
            f"issuer={_issuer!s}, "
            f"issuer_country={_issuer_country!s}, "
            f"response_code={_response_code!s}, "
            f"auth_code={_auth_code!s}, "
            f"avs_result={_avs_result!s}, "
            f"avs_house_number_result={_avs_house_number_result!s}, "
            f"avs_postcode_result={_avs_postcode_result!s}, "
            f"csc_result={_csc_result!s}, "
            f"payer_authentication_result={_payer_authentication_result!s}, "
            f"payer_ip={_payer_ip!s}, "
            f"payer_name={_payer_name!s}, "
            f"payer_email={_payer_email!s}, "
            f"payer_phone={_payer_phone!s}, "
            f"ip_country={_ip_country!s}, "
            f"ip_city={_ip_city!s}, "
            f"ip_latitude={_ip_latitude!s}, "
            f"ip_longitude={_ip_longitude!s}, "
            f"merchant_custom_data={_merchant_custom_data!s}, "
            f"description={_description!s}, "
            f"parent_transaction_id={_parent_transaction_id!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
