"""dnapaymentspartnerreportingsettlementapis.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from dnapaymentspartnerreportingsettlementapis.api_helper import (
    APIHelper,
)
from dnapaymentspartnerreportingsettlementapis.models.terminal import (
    Terminal,
)


class MerchantV2(object):
    """Implementation of the 'MerchantV2' model.

    Attributes:
        descriptor (str): Merchant descriptor as it appears on the consumer's bank
            statement for DNA Acquiring.
        id (str): Unique ID for the merchant, allocated by DNA Payments.
        name (str): Name of the merchant.
        is_active (bool): Whether the merchant is active.
        reconciliation_id (str): Unique ID allocated by DNA Payments to the merchant
            account; appears on the merchant bank statement when payments/settlements
            are made.
        terminals (List[Terminal]): List of all Terminal IDs configured for the
            merchant.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "descriptor": "descriptor",
        "id": "id",
        "name": "name",
        "is_active": "isActive",
        "reconciliation_id": "reconciliationId",
        "terminals": "terminals",
    }

    _optionals = [
        "descriptor",
        "id",
        "name",
        "is_active",
        "reconciliation_id",
        "terminals",
    ]

    def __init__(
        self,
        descriptor=APIHelper.SKIP,
        id=APIHelper.SKIP,
        name=APIHelper.SKIP,
        is_active=APIHelper.SKIP,
        reconciliation_id=APIHelper.SKIP,
        terminals=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a MerchantV2 instance."""
        # Initialize members of the class
        if descriptor is not APIHelper.SKIP:
            self.descriptor = descriptor
        if id is not APIHelper.SKIP:
            self.id = id
        if name is not APIHelper.SKIP:
            self.name = name
        if is_active is not APIHelper.SKIP:
            self.is_active = is_active
        if reconciliation_id is not APIHelper.SKIP:
            self.reconciliation_id = reconciliation_id
        if terminals is not APIHelper.SKIP:
            self.terminals = terminals

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        descriptor =\
            dictionary.get("descriptor")\
            if dictionary.get("descriptor")\
                else APIHelper.SKIP
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else APIHelper.SKIP
        name =\
            dictionary.get("name")\
            if dictionary.get("name")\
                else APIHelper.SKIP
        is_active =\
            dictionary.get("isActive")\
            if "isActive" in dictionary.keys()\
                else APIHelper.SKIP
        reconciliation_id =\
            dictionary.get("reconciliationId")\
            if dictionary.get("reconciliationId")\
                else APIHelper.SKIP
        terminals = None
        if dictionary.get("terminals") is not None:
            terminals = [
                Terminal.from_dictionary(x)
                    for x in dictionary.get("terminals")
            ]
        else:
            terminals = APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(descriptor,
                   id,
                   name,
                   is_active,
                   reconciliation_id,
                   terminals,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _descriptor=(
            self.descriptor
            if hasattr(self, "descriptor")
            else None
        )
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _name=(
            self.name
            if hasattr(self, "name")
            else None
        )
        _is_active=(
            self.is_active
            if hasattr(self, "is_active")
            else None
        )
        _reconciliation_id=(
            self.reconciliation_id
            if hasattr(self, "reconciliation_id")
            else None
        )
        _terminals=(
            self.terminals
            if hasattr(self, "terminals")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"descriptor={_descriptor!r}, "
            f"id={_id!r}, "
            f"name={_name!r}, "
            f"is_active={_is_active!r}, "
            f"reconciliation_id={_reconciliation_id!r}, "
            f"terminals={_terminals!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _descriptor=(
            self.descriptor
            if hasattr(self, "descriptor")
            else None
        )
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _name=(
            self.name
            if hasattr(self, "name")
            else None
        )
        _is_active=(
            self.is_active
            if hasattr(self, "is_active")
            else None
        )
        _reconciliation_id=(
            self.reconciliation_id
            if hasattr(self, "reconciliation_id")
            else None
        )
        _terminals=(
            self.terminals
            if hasattr(self, "terminals")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"descriptor={_descriptor!s}, "
            f"id={_id!s}, "
            f"name={_name!s}, "
            f"is_active={_is_active!s}, "
            f"reconciliation_id={_reconciliation_id!s}, "
            f"terminals={_terminals!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
