"""dnapaymentspartnerreportingsettlementapis.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class Operation(object):
    """Implementation of the 'Operation' enum.

    Confirmation of the operation performed.

    Attributes:
        ADVICE: The enum member of type str.
        REVERSAL: The enum member of type str.
        ADJUSTMENT: The enum member of type str.
        REQUEST: The enum member of type str.
        PARTADVICE: The enum member of type str.

    """

    ADVICE = "advice"

    REVERSAL = "reversal"

    ADJUSTMENT = "adjustment"

    REQUEST = "request"

    PARTADVICE = "part-advice"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
