"""dnapaymentspartnerreportingsettlementapis.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from dnapaymentspartnerreportingsettlementapis.api_helper import (
    APIHelper,
)


class PosTransaction(object):
    """Implementation of the 'PosTransaction' model.

    Attributes:
        merchant_id (str): Unique ID for the merchant, allocated by DNA Payments.
        merchant_name (str): Name of the merchant.
        transaction_date (datetime): Date/time the transaction was created on the DNA
            Platform.
        amount (float): Transaction amount.
        currency (str): Transaction currency code. ISO 4217 format, e.g. GBP.
        status (Status1): success: successful transaction. failed: failed transaction.
        return_code (str): Response code returned by the Acquirer during the
            authorisation process.
        return_code_description (str): Description of the returnCode returned by the
            Acquirer.
        transaction_id (str): Unique ID allocated to the transaction.
        terminal_id (str): Unique Terminal ID for the merchant, allocated by DNA
            Payments.
        operation (Operation): Confirmation of the operation performed.
        transaction_type (TransactionType): Type of transaction/fee recorded in the
            Settlement (and, by reference, POS Reporting) API.
        transaction_country (str): Country where the transaction was processed.
        transaction_city (str): City where the transaction was processed.
        card_scheme (str): Card scheme used in the transaction, e.g. mastercard, visa.
        card_mask (str): Masked PAN for the payment card used; contains the first six
            and last four digits.
        card_type (str): Type of card used in the transaction.
        is_european_card (bool): Whether the card used was issued in Europe
            (including the UK).
        is_corporate_card (bool): Whether the card used is a corporate card.
        capture_method (CaptureMethod): Capture method for the transaction.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "merchant_id": "merchantId",
        "merchant_name": "merchantName",
        "transaction_date": "transactionDate",
        "amount": "amount",
        "currency": "currency",
        "status": "status",
        "return_code": "returnCode",
        "return_code_description": "returnCodeDescription",
        "transaction_id": "transactionId",
        "terminal_id": "terminalId",
        "operation": "operation",
        "transaction_type": "transactionType",
        "transaction_country": "transactionCountry",
        "transaction_city": "transactionCity",
        "card_scheme": "cardScheme",
        "card_mask": "cardMask",
        "card_type": "cardType",
        "is_european_card": "isEuropeanCard",
        "is_corporate_card": "isCorporateCard",
        "capture_method": "captureMethod",
    }

    _optionals = [
        "merchant_id",
        "merchant_name",
        "transaction_date",
        "amount",
        "currency",
        "status",
        "return_code",
        "return_code_description",
        "transaction_id",
        "terminal_id",
        "operation",
        "transaction_type",
        "transaction_country",
        "transaction_city",
        "card_scheme",
        "card_mask",
        "card_type",
        "is_european_card",
        "is_corporate_card",
        "capture_method",
    ]

    _nullables = [
        "transaction_country",
        "transaction_city",
        "card_scheme",
        "card_mask",
        "card_type",
        "is_european_card",
        "is_corporate_card",
        "capture_method",
    ]

    def __init__(
        self,
        merchant_id=APIHelper.SKIP,
        merchant_name=APIHelper.SKIP,
        transaction_date=APIHelper.SKIP,
        amount=APIHelper.SKIP,
        currency=APIHelper.SKIP,
        status=APIHelper.SKIP,
        return_code=APIHelper.SKIP,
        return_code_description=APIHelper.SKIP,
        transaction_id=APIHelper.SKIP,
        terminal_id=APIHelper.SKIP,
        operation=APIHelper.SKIP,
        transaction_type=APIHelper.SKIP,
        transaction_country=APIHelper.SKIP,
        transaction_city=APIHelper.SKIP,
        card_scheme=APIHelper.SKIP,
        card_mask=APIHelper.SKIP,
        card_type=APIHelper.SKIP,
        is_european_card=APIHelper.SKIP,
        is_corporate_card=APIHelper.SKIP,
        capture_method=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a PosTransaction instance."""
        # Initialize members of the class
        if merchant_id is not APIHelper.SKIP:
            self.merchant_id = merchant_id
        if merchant_name is not APIHelper.SKIP:
            self.merchant_name = merchant_name
        if transaction_date is not APIHelper.SKIP:
            self.transaction_date =\
                 APIHelper.apply_datetime_converter(
                transaction_date, APIHelper.RFC3339DateTime)\
                 if transaction_date else None
        if amount is not APIHelper.SKIP:
            self.amount = amount
        if currency is not APIHelper.SKIP:
            self.currency = currency
        if status is not APIHelper.SKIP:
            self.status = status
        if return_code is not APIHelper.SKIP:
            self.return_code = return_code
        if return_code_description is not APIHelper.SKIP:
            self.return_code_description = return_code_description
        if transaction_id is not APIHelper.SKIP:
            self.transaction_id = transaction_id
        if terminal_id is not APIHelper.SKIP:
            self.terminal_id = terminal_id
        if operation is not APIHelper.SKIP:
            self.operation = operation
        if transaction_type is not APIHelper.SKIP:
            self.transaction_type = transaction_type
        if transaction_country is not APIHelper.SKIP:
            self.transaction_country = transaction_country
        if transaction_city is not APIHelper.SKIP:
            self.transaction_city = transaction_city
        if card_scheme is not APIHelper.SKIP:
            self.card_scheme = card_scheme
        if card_mask is not APIHelper.SKIP:
            self.card_mask = card_mask
        if card_type is not APIHelper.SKIP:
            self.card_type = card_type
        if is_european_card is not APIHelper.SKIP:
            self.is_european_card = is_european_card
        if is_corporate_card is not APIHelper.SKIP:
            self.is_corporate_card = is_corporate_card
        if capture_method is not APIHelper.SKIP:
            self.capture_method = capture_method

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        merchant_id =\
            dictionary.get("merchantId")\
            if dictionary.get("merchantId")\
                else APIHelper.SKIP
        merchant_name =\
            dictionary.get("merchantName")\
            if dictionary.get("merchantName")\
                else APIHelper.SKIP
        transaction_date = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("transactionDate")).datetime\
            if dictionary.get("transactionDate") else APIHelper.SKIP
        amount =\
            dictionary.get("amount")\
            if dictionary.get("amount")\
                else APIHelper.SKIP
        currency =\
            dictionary.get("currency")\
            if dictionary.get("currency")\
                else APIHelper.SKIP
        status =\
            dictionary.get("status")\
            if dictionary.get("status")\
                else APIHelper.SKIP
        return_code =\
            dictionary.get("returnCode")\
            if dictionary.get("returnCode")\
                else APIHelper.SKIP
        return_code_description =\
            dictionary.get("returnCodeDescription")\
            if dictionary.get("returnCodeDescription")\
                else APIHelper.SKIP
        transaction_id =\
            dictionary.get("transactionId")\
            if dictionary.get("transactionId")\
                else APIHelper.SKIP
        terminal_id =\
            dictionary.get("terminalId")\
            if dictionary.get("terminalId")\
                else APIHelper.SKIP
        operation =\
            dictionary.get("operation")\
            if dictionary.get("operation")\
                else APIHelper.SKIP
        transaction_type =\
            dictionary.get("transactionType")\
            if dictionary.get("transactionType")\
                else APIHelper.SKIP
        transaction_country =\
            dictionary.get("transactionCountry")\
            if "transactionCountry" in dictionary.keys()\
                else APIHelper.SKIP
        transaction_city =\
            dictionary.get("transactionCity")\
            if "transactionCity" in dictionary.keys()\
                else APIHelper.SKIP
        card_scheme =\
            dictionary.get("cardScheme")\
            if "cardScheme" in dictionary.keys()\
                else APIHelper.SKIP
        card_mask =\
            dictionary.get("cardMask")\
            if "cardMask" in dictionary.keys()\
                else APIHelper.SKIP
        card_type =\
            dictionary.get("cardType")\
            if "cardType" in dictionary.keys()\
                else APIHelper.SKIP
        is_european_card =\
            dictionary.get("isEuropeanCard")\
            if "isEuropeanCard" in dictionary.keys()\
                else APIHelper.SKIP
        is_corporate_card =\
            dictionary.get("isCorporateCard")\
            if "isCorporateCard" in dictionary.keys()\
                else APIHelper.SKIP
        capture_method =\
            dictionary.get("captureMethod")\
            if "captureMethod" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(merchant_id,
                   merchant_name,
                   transaction_date,
                   amount,
                   currency,
                   status,
                   return_code,
                   return_code_description,
                   transaction_id,
                   terminal_id,
                   operation,
                   transaction_type,
                   transaction_country,
                   transaction_city,
                   card_scheme,
                   card_mask,
                   card_type,
                   is_european_card,
                   is_corporate_card,
                   capture_method,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _merchant_id=(
            self.merchant_id
            if hasattr(self, "merchant_id")
            else None
        )
        _merchant_name=(
            self.merchant_name
            if hasattr(self, "merchant_name")
            else None
        )
        _transaction_date=(
            self.transaction_date
            if hasattr(self, "transaction_date")
            else None
        )
        _amount=(
            self.amount
            if hasattr(self, "amount")
            else None
        )
        _currency=(
            self.currency
            if hasattr(self, "currency")
            else None
        )
        _status=(
            self.status
            if hasattr(self, "status")
            else None
        )
        _return_code=(
            self.return_code
            if hasattr(self, "return_code")
            else None
        )
        _return_code_description=(
            self.return_code_description
            if hasattr(self, "return_code_description")
            else None
        )
        _transaction_id=(
            self.transaction_id
            if hasattr(self, "transaction_id")
            else None
        )
        _terminal_id=(
            self.terminal_id
            if hasattr(self, "terminal_id")
            else None
        )
        _operation=(
            self.operation
            if hasattr(self, "operation")
            else None
        )
        _transaction_type=(
            self.transaction_type
            if hasattr(self, "transaction_type")
            else None
        )
        _transaction_country=(
            self.transaction_country
            if hasattr(self, "transaction_country")
            else None
        )
        _transaction_city=(
            self.transaction_city
            if hasattr(self, "transaction_city")
            else None
        )
        _card_scheme=(
            self.card_scheme
            if hasattr(self, "card_scheme")
            else None
        )
        _card_mask=(
            self.card_mask
            if hasattr(self, "card_mask")
            else None
        )
        _card_type=(
            self.card_type
            if hasattr(self, "card_type")
            else None
        )
        _is_european_card=(
            self.is_european_card
            if hasattr(self, "is_european_card")
            else None
        )
        _is_corporate_card=(
            self.is_corporate_card
            if hasattr(self, "is_corporate_card")
            else None
        )
        _capture_method=(
            self.capture_method
            if hasattr(self, "capture_method")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"merchant_id={_merchant_id!r}, "
            f"merchant_name={_merchant_name!r}, "
            f"transaction_date={_transaction_date!r}, "
            f"amount={_amount!r}, "
            f"currency={_currency!r}, "
            f"status={_status!r}, "
            f"return_code={_return_code!r}, "
            f"return_code_description={_return_code_description!r}, "
            f"transaction_id={_transaction_id!r}, "
            f"terminal_id={_terminal_id!r}, "
            f"operation={_operation!r}, "
            f"transaction_type={_transaction_type!r}, "
            f"transaction_country={_transaction_country!r}, "
            f"transaction_city={_transaction_city!r}, "
            f"card_scheme={_card_scheme!r}, "
            f"card_mask={_card_mask!r}, "
            f"card_type={_card_type!r}, "
            f"is_european_card={_is_european_card!r}, "
            f"is_corporate_card={_is_corporate_card!r}, "
            f"capture_method={_capture_method!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _merchant_id=(
            self.merchant_id
            if hasattr(self, "merchant_id")
            else None
        )
        _merchant_name=(
            self.merchant_name
            if hasattr(self, "merchant_name")
            else None
        )
        _transaction_date=(
            self.transaction_date
            if hasattr(self, "transaction_date")
            else None
        )
        _amount=(
            self.amount
            if hasattr(self, "amount")
            else None
        )
        _currency=(
            self.currency
            if hasattr(self, "currency")
            else None
        )
        _status=(
            self.status
            if hasattr(self, "status")
            else None
        )
        _return_code=(
            self.return_code
            if hasattr(self, "return_code")
            else None
        )
        _return_code_description=(
            self.return_code_description
            if hasattr(self, "return_code_description")
            else None
        )
        _transaction_id=(
            self.transaction_id
            if hasattr(self, "transaction_id")
            else None
        )
        _terminal_id=(
            self.terminal_id
            if hasattr(self, "terminal_id")
            else None
        )
        _operation=(
            self.operation
            if hasattr(self, "operation")
            else None
        )
        _transaction_type=(
            self.transaction_type
            if hasattr(self, "transaction_type")
            else None
        )
        _transaction_country=(
            self.transaction_country
            if hasattr(self, "transaction_country")
            else None
        )
        _transaction_city=(
            self.transaction_city
            if hasattr(self, "transaction_city")
            else None
        )
        _card_scheme=(
            self.card_scheme
            if hasattr(self, "card_scheme")
            else None
        )
        _card_mask=(
            self.card_mask
            if hasattr(self, "card_mask")
            else None
        )
        _card_type=(
            self.card_type
            if hasattr(self, "card_type")
            else None
        )
        _is_european_card=(
            self.is_european_card
            if hasattr(self, "is_european_card")
            else None
        )
        _is_corporate_card=(
            self.is_corporate_card
            if hasattr(self, "is_corporate_card")
            else None
        )
        _capture_method=(
            self.capture_method
            if hasattr(self, "capture_method")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"merchant_id={_merchant_id!s}, "
            f"merchant_name={_merchant_name!s}, "
            f"transaction_date={_transaction_date!s}, "
            f"amount={_amount!s}, "
            f"currency={_currency!s}, "
            f"status={_status!s}, "
            f"return_code={_return_code!s}, "
            f"return_code_description={_return_code_description!s}, "
            f"transaction_id={_transaction_id!s}, "
            f"terminal_id={_terminal_id!s}, "
            f"operation={_operation!s}, "
            f"transaction_type={_transaction_type!s}, "
            f"transaction_country={_transaction_country!s}, "
            f"transaction_city={_transaction_city!s}, "
            f"card_scheme={_card_scheme!s}, "
            f"card_mask={_card_mask!s}, "
            f"card_type={_card_type!s}, "
            f"is_european_card={_is_european_card!s}, "
            f"is_corporate_card={_is_corporate_card!s}, "
            f"capture_method={_capture_method!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
