"""dnapaymentspartnerreportingsettlementapis.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
import dateutil.parser

from dnapaymentspartnerreportingsettlementapis.api_helper import (
    APIHelper,
)


class Settlement(object):
    """Implementation of the 'Settlement' model.

    Attributes:
        processed_date (date): Date that the settlement process was started.
        settlement_date (date): Date that the transaction was settled.
        merchant_id (str): Unique ID for the merchant, allocated by DNA Payments.
        merchant_name (str): Name of the merchant who processed the transaction.
        amount (float): Original requested transaction amount.
        acquirer_fee (float): Acquiring fee charged for processing the transaction.
        amount_to_merchant (float): Amount settled to the merchant.
        currency (str): Currency of the transaction, e.g. GBP.
        operation (Operation): Confirmation of the operation performed.
        transaction_id (str): Unique transaction ID. Null for non-transactional fees.
        transaction_date (datetime): Date/time the transaction was processed.
        transaction_type (TransactionType): Type of transaction/fee recorded in the
            Settlement (and, by reference, POS Reporting) API.
        merchant_reference (str): Unique order number allocated by the merchant.
        card_scheme (str): Card scheme used in the transaction.
        card_type (CardType): Type of card used in the transaction.
        is_european_card (bool): Whether the card used is issued in Europe (including
            the UK).
        is_corporate_card (bool): Whether the card used is a corporate card.
        card_mask (str): Masked PAN for the payment card used; contains the first six
            and last four digits.
        capture_method (CaptureMethod): Capture method for the transaction.
        issuer_country (str): Country in which the payment card was issued. ISO
            3166-1 alpha-3. Null if it cannot be determined.
        merchant_custom_data (str): Custom data provided by the integrated solution
            for the transaction.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "processed_date": "processedDate",
        "settlement_date": "settlementDate",
        "merchant_id": "merchantId",
        "merchant_name": "merchantName",
        "amount": "amount",
        "acquirer_fee": "acquirerFee",
        "amount_to_merchant": "amountToMerchant",
        "currency": "currency",
        "operation": "operation",
        "transaction_id": "transactionId",
        "transaction_date": "transactionDate",
        "transaction_type": "transactionType",
        "merchant_reference": "merchantReference",
        "card_scheme": "cardScheme",
        "card_type": "cardType",
        "is_european_card": "isEuropeanCard",
        "is_corporate_card": "isCorporateCard",
        "card_mask": "cardMask",
        "capture_method": "captureMethod",
        "issuer_country": "issuerCountry",
        "merchant_custom_data": "merchantCustomData",
    }

    _optionals = [
        "processed_date",
        "settlement_date",
        "merchant_id",
        "merchant_name",
        "amount",
        "acquirer_fee",
        "amount_to_merchant",
        "currency",
        "operation",
        "transaction_id",
        "transaction_date",
        "transaction_type",
        "merchant_reference",
        "card_scheme",
        "card_type",
        "is_european_card",
        "is_corporate_card",
        "card_mask",
        "capture_method",
        "issuer_country",
        "merchant_custom_data",
    ]

    _nullables = [
        "settlement_date",
        "transaction_id",
        "merchant_reference",
        "card_scheme",
        "card_type",
        "is_european_card",
        "is_corporate_card",
        "card_mask",
        "capture_method",
        "issuer_country",
        "merchant_custom_data",
    ]

    def __init__(
        self,
        processed_date=APIHelper.SKIP,
        settlement_date=APIHelper.SKIP,
        merchant_id=APIHelper.SKIP,
        merchant_name=APIHelper.SKIP,
        amount=APIHelper.SKIP,
        acquirer_fee=APIHelper.SKIP,
        amount_to_merchant=APIHelper.SKIP,
        currency=APIHelper.SKIP,
        operation=APIHelper.SKIP,
        transaction_id=APIHelper.SKIP,
        transaction_date=APIHelper.SKIP,
        transaction_type=APIHelper.SKIP,
        merchant_reference=APIHelper.SKIP,
        card_scheme=APIHelper.SKIP,
        card_type=APIHelper.SKIP,
        is_european_card=APIHelper.SKIP,
        is_corporate_card=APIHelper.SKIP,
        card_mask=APIHelper.SKIP,
        capture_method=APIHelper.SKIP,
        issuer_country=APIHelper.SKIP,
        merchant_custom_data=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a Settlement instance."""
        # Initialize members of the class
        if processed_date is not APIHelper.SKIP:
            self.processed_date = processed_date
        if settlement_date is not APIHelper.SKIP:
            self.settlement_date = settlement_date
        if merchant_id is not APIHelper.SKIP:
            self.merchant_id = merchant_id
        if merchant_name is not APIHelper.SKIP:
            self.merchant_name = merchant_name
        if amount is not APIHelper.SKIP:
            self.amount = amount
        if acquirer_fee is not APIHelper.SKIP:
            self.acquirer_fee = acquirer_fee
        if amount_to_merchant is not APIHelper.SKIP:
            self.amount_to_merchant = amount_to_merchant
        if currency is not APIHelper.SKIP:
            self.currency = currency
        if operation is not APIHelper.SKIP:
            self.operation = operation
        if transaction_id is not APIHelper.SKIP:
            self.transaction_id = transaction_id
        if transaction_date is not APIHelper.SKIP:
            self.transaction_date =\
                 APIHelper.apply_datetime_converter(
                transaction_date, APIHelper.RFC3339DateTime)\
                 if transaction_date else None
        if transaction_type is not APIHelper.SKIP:
            self.transaction_type = transaction_type
        if merchant_reference is not APIHelper.SKIP:
            self.merchant_reference = merchant_reference
        if card_scheme is not APIHelper.SKIP:
            self.card_scheme = card_scheme
        if card_type is not APIHelper.SKIP:
            self.card_type = card_type
        if is_european_card is not APIHelper.SKIP:
            self.is_european_card = is_european_card
        if is_corporate_card is not APIHelper.SKIP:
            self.is_corporate_card = is_corporate_card
        if card_mask is not APIHelper.SKIP:
            self.card_mask = card_mask
        if capture_method is not APIHelper.SKIP:
            self.capture_method = capture_method
        if issuer_country is not APIHelper.SKIP:
            self.issuer_country = issuer_country
        if merchant_custom_data is not APIHelper.SKIP:
            self.merchant_custom_data = merchant_custom_data

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        processed_date = dateutil.parser.parse(
            dictionary.get("processedDate")).date()\
            if dictionary.get("processedDate") else APIHelper.SKIP
        if "settlementDate" in dictionary.keys():
            settlement_date = dateutil.parser.parse(
                dictionary.get("settlementDate")).date()\
                if dictionary.get("settlementDate") else None

        else:
            settlement_date = APIHelper.SKIP
        merchant_id =\
            dictionary.get("merchantId")\
            if dictionary.get("merchantId")\
                else APIHelper.SKIP
        merchant_name =\
            dictionary.get("merchantName")\
            if dictionary.get("merchantName")\
                else APIHelper.SKIP
        amount =\
            dictionary.get("amount")\
            if dictionary.get("amount")\
                else APIHelper.SKIP
        acquirer_fee =\
            dictionary.get("acquirerFee")\
            if dictionary.get("acquirerFee")\
                else APIHelper.SKIP
        amount_to_merchant =\
            dictionary.get("amountToMerchant")\
            if dictionary.get("amountToMerchant")\
                else APIHelper.SKIP
        currency =\
            dictionary.get("currency")\
            if dictionary.get("currency")\
                else APIHelper.SKIP
        operation =\
            dictionary.get("operation")\
            if dictionary.get("operation")\
                else APIHelper.SKIP
        transaction_id =\
            dictionary.get("transactionId")\
            if "transactionId" in dictionary.keys()\
                else APIHelper.SKIP
        transaction_date = APIHelper.RFC3339DateTime.from_value(
            dictionary.get("transactionDate")).datetime\
            if dictionary.get("transactionDate") else APIHelper.SKIP
        transaction_type =\
            dictionary.get("transactionType")\
            if dictionary.get("transactionType")\
                else APIHelper.SKIP
        merchant_reference =\
            dictionary.get("merchantReference")\
            if "merchantReference" in dictionary.keys()\
                else APIHelper.SKIP
        card_scheme =\
            dictionary.get("cardScheme")\
            if "cardScheme" in dictionary.keys()\
                else APIHelper.SKIP
        card_type =\
            dictionary.get("cardType")\
            if "cardType" in dictionary.keys()\
                else APIHelper.SKIP
        is_european_card =\
            dictionary.get("isEuropeanCard")\
            if "isEuropeanCard" in dictionary.keys()\
                else APIHelper.SKIP
        is_corporate_card =\
            dictionary.get("isCorporateCard")\
            if "isCorporateCard" in dictionary.keys()\
                else APIHelper.SKIP
        card_mask =\
            dictionary.get("cardMask")\
            if "cardMask" in dictionary.keys()\
                else APIHelper.SKIP
        capture_method =\
            dictionary.get("captureMethod")\
            if "captureMethod" in dictionary.keys()\
                else APIHelper.SKIP
        issuer_country =\
            dictionary.get("issuerCountry")\
            if "issuerCountry" in dictionary.keys()\
                else APIHelper.SKIP
        merchant_custom_data =\
            dictionary.get("merchantCustomData")\
            if "merchantCustomData" in dictionary.keys()\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(processed_date,
                   settlement_date,
                   merchant_id,
                   merchant_name,
                   amount,
                   acquirer_fee,
                   amount_to_merchant,
                   currency,
                   operation,
                   transaction_id,
                   transaction_date,
                   transaction_type,
                   merchant_reference,
                   card_scheme,
                   card_type,
                   is_european_card,
                   is_corporate_card,
                   card_mask,
                   capture_method,
                   issuer_country,
                   merchant_custom_data,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _processed_date=(
            self.processed_date
            if hasattr(self, "processed_date")
            else None
        )
        _settlement_date=(
            self.settlement_date
            if hasattr(self, "settlement_date")
            else None
        )
        _merchant_id=(
            self.merchant_id
            if hasattr(self, "merchant_id")
            else None
        )
        _merchant_name=(
            self.merchant_name
            if hasattr(self, "merchant_name")
            else None
        )
        _amount=(
            self.amount
            if hasattr(self, "amount")
            else None
        )
        _acquirer_fee=(
            self.acquirer_fee
            if hasattr(self, "acquirer_fee")
            else None
        )
        _amount_to_merchant=(
            self.amount_to_merchant
            if hasattr(self, "amount_to_merchant")
            else None
        )
        _currency=(
            self.currency
            if hasattr(self, "currency")
            else None
        )
        _operation=(
            self.operation
            if hasattr(self, "operation")
            else None
        )
        _transaction_id=(
            self.transaction_id
            if hasattr(self, "transaction_id")
            else None
        )
        _transaction_date=(
            self.transaction_date
            if hasattr(self, "transaction_date")
            else None
        )
        _transaction_type=(
            self.transaction_type
            if hasattr(self, "transaction_type")
            else None
        )
        _merchant_reference=(
            self.merchant_reference
            if hasattr(self, "merchant_reference")
            else None
        )
        _card_scheme=(
            self.card_scheme
            if hasattr(self, "card_scheme")
            else None
        )
        _card_type=(
            self.card_type
            if hasattr(self, "card_type")
            else None
        )
        _is_european_card=(
            self.is_european_card
            if hasattr(self, "is_european_card")
            else None
        )
        _is_corporate_card=(
            self.is_corporate_card
            if hasattr(self, "is_corporate_card")
            else None
        )
        _card_mask=(
            self.card_mask
            if hasattr(self, "card_mask")
            else None
        )
        _capture_method=(
            self.capture_method
            if hasattr(self, "capture_method")
            else None
        )
        _issuer_country=(
            self.issuer_country
            if hasattr(self, "issuer_country")
            else None
        )
        _merchant_custom_data=(
            self.merchant_custom_data
            if hasattr(self, "merchant_custom_data")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"processed_date={_processed_date!r}, "
            f"settlement_date={_settlement_date!r}, "
            f"merchant_id={_merchant_id!r}, "
            f"merchant_name={_merchant_name!r}, "
            f"amount={_amount!r}, "
            f"acquirer_fee={_acquirer_fee!r}, "
            f"amount_to_merchant={_amount_to_merchant!r}, "
            f"currency={_currency!r}, "
            f"operation={_operation!r}, "
            f"transaction_id={_transaction_id!r}, "
            f"transaction_date={_transaction_date!r}, "
            f"transaction_type={_transaction_type!r}, "
            f"merchant_reference={_merchant_reference!r}, "
            f"card_scheme={_card_scheme!r}, "
            f"card_type={_card_type!r}, "
            f"is_european_card={_is_european_card!r}, "
            f"is_corporate_card={_is_corporate_card!r}, "
            f"card_mask={_card_mask!r}, "
            f"capture_method={_capture_method!r}, "
            f"issuer_country={_issuer_country!r}, "
            f"merchant_custom_data={_merchant_custom_data!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _processed_date=(
            self.processed_date
            if hasattr(self, "processed_date")
            else None
        )
        _settlement_date=(
            self.settlement_date
            if hasattr(self, "settlement_date")
            else None
        )
        _merchant_id=(
            self.merchant_id
            if hasattr(self, "merchant_id")
            else None
        )
        _merchant_name=(
            self.merchant_name
            if hasattr(self, "merchant_name")
            else None
        )
        _amount=(
            self.amount
            if hasattr(self, "amount")
            else None
        )
        _acquirer_fee=(
            self.acquirer_fee
            if hasattr(self, "acquirer_fee")
            else None
        )
        _amount_to_merchant=(
            self.amount_to_merchant
            if hasattr(self, "amount_to_merchant")
            else None
        )
        _currency=(
            self.currency
            if hasattr(self, "currency")
            else None
        )
        _operation=(
            self.operation
            if hasattr(self, "operation")
            else None
        )
        _transaction_id=(
            self.transaction_id
            if hasattr(self, "transaction_id")
            else None
        )
        _transaction_date=(
            self.transaction_date
            if hasattr(self, "transaction_date")
            else None
        )
        _transaction_type=(
            self.transaction_type
            if hasattr(self, "transaction_type")
            else None
        )
        _merchant_reference=(
            self.merchant_reference
            if hasattr(self, "merchant_reference")
            else None
        )
        _card_scheme=(
            self.card_scheme
            if hasattr(self, "card_scheme")
            else None
        )
        _card_type=(
            self.card_type
            if hasattr(self, "card_type")
            else None
        )
        _is_european_card=(
            self.is_european_card
            if hasattr(self, "is_european_card")
            else None
        )
        _is_corporate_card=(
            self.is_corporate_card
            if hasattr(self, "is_corporate_card")
            else None
        )
        _card_mask=(
            self.card_mask
            if hasattr(self, "card_mask")
            else None
        )
        _capture_method=(
            self.capture_method
            if hasattr(self, "capture_method")
            else None
        )
        _issuer_country=(
            self.issuer_country
            if hasattr(self, "issuer_country")
            else None
        )
        _merchant_custom_data=(
            self.merchant_custom_data
            if hasattr(self, "merchant_custom_data")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"processed_date={_processed_date!s}, "
            f"settlement_date={_settlement_date!s}, "
            f"merchant_id={_merchant_id!s}, "
            f"merchant_name={_merchant_name!s}, "
            f"amount={_amount!s}, "
            f"acquirer_fee={_acquirer_fee!s}, "
            f"amount_to_merchant={_amount_to_merchant!s}, "
            f"currency={_currency!s}, "
            f"operation={_operation!s}, "
            f"transaction_id={_transaction_id!s}, "
            f"transaction_date={_transaction_date!s}, "
            f"transaction_type={_transaction_type!s}, "
            f"merchant_reference={_merchant_reference!s}, "
            f"card_scheme={_card_scheme!s}, "
            f"card_type={_card_type!s}, "
            f"is_european_card={_is_european_card!s}, "
            f"is_corporate_card={_is_corporate_card!s}, "
            f"card_mask={_card_mask!s}, "
            f"capture_method={_capture_method!s}, "
            f"issuer_country={_issuer_country!s}, "
            f"merchant_custom_data={_merchant_custom_data!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
