"""dnapaymentspartnerreportingsettlementapis.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from dnapaymentspartnerreportingsettlementapis.api_helper import (
    APIHelper,
)


class Terminal(object):
    """Implementation of the 'Terminal' model.

    Attributes:
        id (str): Unique Terminal ID for the merchant, allocated by DNA Payments.
        mid (str): MID allocated by DNA Payments. Available only for the pos terminal
            type.
        daily_settlement (bool): If true, a separate payment is received each day. If
            false, a single payment is received on Monday for the entire weekend
            (Fri/Sat/Sun combined).
        settlement_period (int): Number of days after which settlement is processed
            for this merchant.
        store_name (str): Name of the merchant store provided during onboarding.
        mtype (Type): Type of terminal: ecom (Ecommerce TID) or pos (physical
            terminal).
        status (Status): open: all operations allowed. suspended/pending-closure:
            merchant-initiated operations prohibited, settlements/disputes still
            allowed. closed: no activity allowed.
        additional_properties (Dict[str, Any]): The additional properties for the
            model.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id": "id",
        "mid": "mid",
        "daily_settlement": "dailySettlement",
        "settlement_period": "settlementPeriod",
        "store_name": "storeName",
        "mtype": "type",
        "status": "status",
    }

    _optionals = [
        "id",
        "mid",
        "daily_settlement",
        "settlement_period",
        "store_name",
        "mtype",
        "status",
    ]

    def __init__(
        self,
        id=APIHelper.SKIP,
        mid=APIHelper.SKIP,
        daily_settlement=APIHelper.SKIP,
        settlement_period=APIHelper.SKIP,
        store_name=APIHelper.SKIP,
        mtype=APIHelper.SKIP,
        status=APIHelper.SKIP,
        additional_properties=None):
        """Initialize a Terminal instance."""
        # Initialize members of the class
        if id is not APIHelper.SKIP:
            self.id = id
        if mid is not APIHelper.SKIP:
            self.mid = mid
        if daily_settlement is not APIHelper.SKIP:
            self.daily_settlement = daily_settlement
        if settlement_period is not APIHelper.SKIP:
            self.settlement_period = settlement_period
        if store_name is not APIHelper.SKIP:
            self.store_name = store_name
        if mtype is not APIHelper.SKIP:
            self.mtype = mtype
        if status is not APIHelper.SKIP:
            self.status = status

        # Add additional model properties to the instance
        if additional_properties is None:
            additional_properties = {}
        self.additional_properties = additional_properties

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Create an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if not isinstance(dictionary, dict) or dictionary is None:
            return None

        # Extract variables from the dictionary
        id =\
            dictionary.get("id")\
            if dictionary.get("id")\
                else APIHelper.SKIP
        mid =\
            dictionary.get("mid")\
            if dictionary.get("mid")\
                else APIHelper.SKIP
        daily_settlement =\
            dictionary.get("dailySettlement")\
            if "dailySettlement" in dictionary.keys()\
                else APIHelper.SKIP
        settlement_period =\
            dictionary.get("settlementPeriod")\
            if dictionary.get("settlementPeriod")\
                else APIHelper.SKIP
        store_name =\
            dictionary.get("storeName")\
            if dictionary.get("storeName")\
                else APIHelper.SKIP
        mtype =\
            dictionary.get("type")\
            if dictionary.get("type")\
                else APIHelper.SKIP
        status =\
            dictionary.get("status")\
            if dictionary.get("status")\
                else APIHelper.SKIP

        additional_properties = APIHelper.get_additional_properties(
            dictionary={k: v for k, v in dictionary.items()
                        if k not in cls._names.values()},
            unboxing_function=lambda value: value)

        # Return an object of this model
        return cls(id,
                   mid,
                   daily_settlement,
                   settlement_period,
                   store_name,
                   mtype,
                   status,
                   additional_properties)

    def __repr__(self):
        """Return a unambiguous string representation."""
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _mid=(
            self.mid
            if hasattr(self, "mid")
            else None
        )
        _daily_settlement=(
            self.daily_settlement
            if hasattr(self, "daily_settlement")
            else None
        )
        _settlement_period=(
            self.settlement_period
            if hasattr(self, "settlement_period")
            else None
        )
        _store_name=(
            self.store_name
            if hasattr(self, "store_name")
            else None
        )
        _mtype=(
            self.mtype
            if hasattr(self, "mtype")
            else None
        )
        _status=(
            self.status
            if hasattr(self, "status")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"id={_id!r}, "
            f"mid={_mid!r}, "
            f"daily_settlement={_daily_settlement!r}, "
            f"settlement_period={_settlement_period!r}, "
            f"store_name={_store_name!r}, "
            f"mtype={_mtype!r}, "
            f"status={_status!r}, "
            f"additional_properties={_additional_properties!r}, "
            f")"
        )

    def __str__(self):
        """Return a human-readable string representation."""
        _id=(
            self.id
            if hasattr(self, "id")
            else None
        )
        _mid=(
            self.mid
            if hasattr(self, "mid")
            else None
        )
        _daily_settlement=(
            self.daily_settlement
            if hasattr(self, "daily_settlement")
            else None
        )
        _settlement_period=(
            self.settlement_period
            if hasattr(self, "settlement_period")
            else None
        )
        _store_name=(
            self.store_name
            if hasattr(self, "store_name")
            else None
        )
        _mtype=(
            self.mtype
            if hasattr(self, "mtype")
            else None
        )
        _status=(
            self.status
            if hasattr(self, "status")
            else None
        )
        _additional_properties=self.additional_properties
        return (
            f"{self.__class__.__name__}("
            f"id={_id!s}, "
            f"mid={_mid!s}, "
            f"daily_settlement={_daily_settlement!s}, "
            f"settlement_period={_settlement_period!s}, "
            f"store_name={_store_name!s}, "
            f"mtype={_mtype!s}, "
            f"status={_status!s}, "
            f"additional_properties={_additional_properties!s}, "
            f")"
        )
