"""dnapaymentspartnerreportingsettlementapis.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501

class TransactionType(object):
    """Implementation of the 'TransactionType' enum.

    Type of transaction/fee recorded in the Settlement (and, by reference, POS
    Reporting) API.

    Attributes:
        RETAIL: The enum member of type str.
        CREDIT: The enum member of type str.
        RETAILAPM: The enum member of type str.
        CREDITAPM: The enum member of type str.
        UNIQUE: The enum member of type str.
        DECLINEDTXN: The enum member of type str.
        MINIMUMMONTHLYSERVICECHARGE: The enum member of type str.
        PCIFEE: The enum member of type str.
        MERCHANTMONTHLYFEE: The enum member of type str.
        MOTOFEE: The enum member of type str.
        ZASHAPPFEE: The enum member of type str.
        AIRTIMESERVICEFEE: The enum member of type str.
        SETTLEMENTFEE: The enum member of type str.
        SETTLEMENTFEETRANS: The enum member of type str.
        ONEOFFTERMINALCOST: The enum member of type str.
        ONEOFFTERMINALSETUPFEE: The enum member of type str.
        MONTHLYRENTFEE: The enum member of type str.
        FASTERFUNDINGMONTHLYFEE: The enum member of type str.
        MONTHLYGATEWAYFEE: The enum member of type str.
        AXEPTSERVICESSUBSCRIPTIONFEES: The enum member of type str.
        ONEOFFCHARGE: The enum member of type str.
        ONEOFFCHARGEWVAT: The enum member of type str.
        RETAILCBK: The enum member of type str.
        CREDITCBK: The enum member of type str.
        RETAIL2PRS: The enum member of type str.
        UNIQUE2PRS: The enum member of type str.
        UNIQUECBK: The enum member of type str.
        ENUM_RETAILCOLLABORATIONRDR: The enum member of type str.
        ADJUSTMENTDUETOMANUALPAYMENT: The enum member of type str.
        ACCOUNTREPLENISHMENT: The enum member of type str.
        NEGATIVEBALANCETODDINVOICE: The enum member of type str.
        CREDITNOTIF: The enum member of type str.
        FEECOLLECTIONOUT: The enum member of type str.
        FEECOLLECTIONINC: The enum member of type str.
        FEECOLLECTIONCBKOUT: The enum member of type str.
        FUNDSDISBOUT: The enum member of type str.
        FUNDSDISBINC: The enum member of type str.
        DEBITACCOUNT: The enum member of type str.
        CREDITACCOUNT: The enum member of type str.
        FEESADJUSTMENT: The enum member of type str.
        HOLDSETTLEMENT: The enum member of type str.
        RELEASEFUNDS: The enum member of type str.
        TRANSFERTOSECURITYDEPOSIT: The enum member of type str.

    """

    RETAIL = "retail"

    CREDIT = "credit"

    RETAILAPM = "retail-apm"

    CREDITAPM = "credit-apm"

    UNIQUE = "unique"

    DECLINEDTXN = "declined-txn"

    MINIMUMMONTHLYSERVICECHARGE = "minimum-monthly-service-charge"

    PCIFEE = "pci-fee"

    MERCHANTMONTHLYFEE = "merchant-monthly-fee"

    MOTOFEE = "moto-fee"

    ZASHAPPFEE = "zash-app-fee"

    AIRTIMESERVICEFEE = "airtime-service-fee"

    SETTLEMENTFEE = "settlement-fee"

    SETTLEMENTFEETRANS = "settlement-fee-trans"

    ONEOFFTERMINALCOST = "one-off-terminal-cost"

    ONEOFFTERMINALSETUPFEE = "one-off-terminal-setup-fee"

    MONTHLYRENTFEE = "monthly-rent-fee"

    FASTERFUNDINGMONTHLYFEE = "faster-funding-monthly-fee"

    MONTHLYGATEWAYFEE = "monthly-gateway-fee"

    AXEPTSERVICESSUBSCRIPTIONFEES = "axept-services-subscription-fees"

    ONEOFFCHARGE = "one-off-charge"

    ONEOFFCHARGEWVAT = "one-off-charge-w-vat"

    RETAILCBK = "retail-cbk"

    CREDITCBK = "credit-cbk"

    RETAIL2PRS = "retail-2prs"

    UNIQUE2PRS = "unique-2prs"

    UNIQUECBK = "unique-cbk"

    ENUM_RETAILCOLLABORATIONRDR = "retail-collaboration/rdr"

    ADJUSTMENTDUETOMANUALPAYMENT = "adjustment-due-to-manual-payment"

    ACCOUNTREPLENISHMENT = "account-replenishment"

    NEGATIVEBALANCETODDINVOICE = "negative-balance-to-dd-invoice"

    CREDITNOTIF = "credit-notif"

    FEECOLLECTIONOUT = "fee-collection-out"

    FEECOLLECTIONINC = "fee-collection-inc"

    FEECOLLECTIONCBKOUT = "fee-collection-cbk-out"

    FUNDSDISBOUT = "funds-disb-out"

    FUNDSDISBINC = "funds-disb-inc"

    DEBITACCOUNT = "debit-account"

    CREDITACCOUNT = "credit-account"

    FEESADJUSTMENT = "fees-adjustment"

    HOLDSETTLEMENT = "hold-settlement"

    RELEASEFUNDS = "release-funds"

    TRANSFERTOSECURITYDEPOSIT = "transfer-to-security-deposit"

    @classmethod
    def from_value(cls, value, default=None):
        """Return the matching enum value for the given input."""
        if value is None:
            return default

        # If numeric and matches directly
        if isinstance(value, int):
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and val == value:
                    return val

        # If string, perform case-insensitive match
        if isinstance(value, str):
            value_lower = value.lower()
            for name, val in cls.__dict__.items():
                if not name.startswith("_") and (
                    name.lower() == value_lower or str(val).lower() == value_lower
                ):
                    return val

        # Fallback to default
        return default
