"""dnapaymentspartnerreportingsettlementapis.

This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
"""

# ruff: noqa: E501
from dnapaymentspartnerreportingsettlementapis.api_helper import (
    APIHelper,
)
from dnapaymentspartnerreportingsettlementapis.exceptions.api_exception import (
    ApiException,
)


class ErrorException(ApiException):
    def __init__(self, reason, response):
        """Initialize ErrorException object.

        Args:
            reason (string): The reason (or error message) for the Exception
                to be raised.
            response (HttpResponse): The HttpResponse of the API call.

        """
        super(ErrorException, self).__init__(reason, response)
        dictionary = APIHelper.json_deserialize(self.response.text)
        if isinstance(dictionary, dict):
            self.unbox(dictionary)

    def unbox(self, dictionary):
        """Populate the properties of this object by extracting them from a dictionary.

        Args:
            dictionary (dictionary): A dictionary representation of the object as
            obtained from the deserialization of the server's response. The keys
            MUST match property names in the API description.

        """
        self.code =\
            dictionary.get("code")\
            if dictionary.get("code")\
                else None
        self.message =\
            dictionary.get("message")\
            if dictionary.get("message")\
                else None


    def __str__(self):
        """Return a human-readable string representation."""
        _code=(
            self.code
            if hasattr(self, "code")
            else None
        )
        _message=(
            self.message
            if hasattr(self, "message")
            else None
        )
        _base_str = super().__str__()
        _base_str = _base_str[_base_str.find("(") + 1:-1]
        return (
            f"{self.__class__.__name__}("
            f"base_str={_base_str!s}, "
            f"code={_code!s}, "
            f"message={_message!s}, "
            f")"
        )
